In [1]:
# 1
v_1 = ['31', '24', '17']
v_2 = v_1.copy()
v_3 = [i for i in ['31', '24', '17']]
v_4 = v_1 + v_2 + v_3
print(v_1, '\n', v_2, '\n', v_3, '\n', v_4)

['31', '24', '17'] 
 ['31', '24', '17'] 
 ['31', '24', '17'] 
 ['31', '24', '17', '31', '24', '17', '31', '24', '17']


In [7]:
#2.1
print([i for i in input('введите строку')])

KeyboardInterrupt: Interrupted by user

In [12]:
#2.2
print([i for i in input('введите предложение').replace(',', '').replace('!', '').replace('.', '').replace('?', '').split()])

введите предложениеПривет, как дела? кто бы ты не был.
['Привет', 'как', 'дела', 'кто', 'бы', 'ты', 'не', 'был']


In [13]:
#2.3
print([i for i in input() if i in '0987654321'])

adhjfal3qhkefah89h3rhkfjalh0qhfahlfd190u
['3', '8', '9', '3', '0', '1', '9', '0']


In [15]:
#3
spisok = ['input', 'string', 'repeat', 3]
if 'repeat' in spisok and str(spisok[-1]).isdigit():
    spisok = spisok[:-2] + spisok[:-2] + spisok[:-2] + spisok[-2:]
print(spisok)
    

['input', 'string', 'input', 'string', 'input', 'string', 'repeat', 3]


In [10]:
#4
s1 = 'sgsd'
s2 = ';ldb'
print(f'Длины строк: {len(s1)} и {len(s2)}')
if s1 != s2:
    print('первая строка идет раньше второй' if max(len(s1), len(s2)) == len(s2) else 'первая строка идет позже второй')
else:
    for i in range(len(s1)):
        if ord(s1[i]) > ord(s2[i]):
            print('первая строка идет раньше второй')
            break
        elif ord(s1[i]) < ord(s2[i]):
            print('первая строка идет раньше второй')

Длины строк: 4 и 4
первая строка идет раньше второй


In [17]:
#5.1
max_var = int(input())
repeat = int(input())
v = []
for j in range(repeat):
    for i in range(1, max_var+1):
        v.append(i)
print(v)


4
4
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [29]:
#5.2
max_var = 10
repeat = int(input())
v = []
for j in range(repeat):
    for i in range(1, max_var+1):
        v.append(i)
print(v)
listcop = v[:]



1324123423


MemoryError: 

In [20]:
#6
stroca = 'test_Stringss'
v = []
for i in range(len(stroca)):
    if stroca[i] in 'Ss' and i != 0 and i != len(stroca)-1:
        v.append(stroca[i-1]+stroca[i-1]+stroca[i+1])
    else:
        v.append(stroca[i])
print(v)
        
        

['t', 'e', 'eet', 't', '_', '__t', 't', 'r', 'i', 'n', 'g', 'ggs', 's']


In [8]:
#7
from math import ceil
def is_digit(s):
    try:
        float(s)
        return True
    except ValueError:
        return False
    
    
v = []
for i in range(10):
    answer = input()
    if answer == 'False':
        v.append(False)
    elif answer == 'True':   
        v.append(True)
    elif is_digit(answer):
        v.append(ceil(float(answer)))
    else:
        v.append(answer)
print(v)

afds
adsf
adsf
23.4
adf
45.5
dsaf
34,6
43.5
afsd
['afds', 'adsf', 'adsf', 24, 'adf', 46, 'dsaf', '34,6', 44, 'afsd']


In [20]:
# 8
stroca_1 = input().split()
stroca_2 = input().split()
v_1 = stroca_1 if len(stroca_1) < len(stroca_2) else stroca_2
v_2 = stroca_1 if len(stroca_2) < len(stroca_1) else stroca_2
v = []
for i in range(len(v_1)):
    v.append(stroca_1[i])
    v.append(stroca_2[i])
v.append(v_2[len(v_1)-1:] if len(v_2) > len(v_1) else '')
print(v)
print(' '.join(v))

asd asd asd
qwe qwe qwe
['asd', 'qwe', 'asd', 'qwe', 'asd', 'qwe', '']
asd qwe asd qwe asd qwe 


In [27]:
# 9
stroca_1 = input().split()
stroca_2 = input().split()
print(list(zip(stroca_1, stroca_2)))
print(' '.join(list(zip(stroca_1, stroca_2))))

asd
qwe
[('asd', 'qwe')]


TypeError: sequence item 0: expected str instance, tuple found

In [34]:
# 10
stroca = input('введите строку').split()
numbers = int(input('число'))
print(' '.join(stroca[numbers+1:] + stroca[:numbers+1]))

введите строкуasd fgh jkl qwe rty uio
число3
rty uio asd fgh jkl qwe


In [8]:
# 11
def prost(a):
    i = 2
    k = []
    while i * i <= a:
        if a % i:
            i += 1
        else:
            a //= i
            k.append(i)
    if a > 1:
        k.append(i)
    return k

v_1 = [1]
for i in range(1, 21):
    if i in [2, 3, 5, 7, 11, 13, 17, 19]:
        v_1.append(i)
    else:
        v_1.extend(prost(i))
print(v_1) 
    
    

[1, 2, 3, 2, 2, 5, 2, 2, 7, 2, 2, 2, 3, 3, 2, 3, 11, 2, 2, 2, 13, 2, 3, 3, 3, 2, 2, 2, 2, 17, 2, 3, 3, 19, 2, 2, 3]


In [9]:
# 12
v = [8, 34, 67, 678, 8, 98, 98, 678, 56]
lst = [i for i in v if v.count(i) == 1]
print(min(lst))

34


In [15]:
# 13
v = [8, 34, 67, 678, 8, 98, 98, 678, 56]
lst = [i for i in v if v.count(i) == 1]
print(*[i for i in range(len(v)) if v[i] == min(lst)])

1


In [16]:
# 14
lst = [1, 6, 68, 990, 1, 98, 98, 6, 56, 1]
print([i for i in range(len(lst)) if lst[i] == 1][-2])

4


In [17]:
# 15
import numpy as np
print(np.array(((2, 3), (4, 5))) @ np.array(((7, 8), (9, 10))))

[[41 46]
 [73 82]]


In [20]:
# 16
from copy import deepcopy
v = np.array(((2, 3), (4, 5)))
m = deepcopy(v)
v[0][0] = 67
print(v, '\n', m)

[[67  3]
 [ 4  5]] 
 [[2 3]
 [4 5]]


In [23]:
# 17
stroc = 'дыня абрикос яблоко арбуз'
print(*sorted(stroc.split()))

абрикос арбуз дыня яблоко


In [28]:
# 18
lsls = [[1, 2, 3], ['a', 'b'], [30, 40, 50, 60]]
maxi = 0
mini = 10 ** 10
for i in range(len(lsls)):
    if len(lsls[i]) > maxi:
        maxi = len(lsls[i])

    if len(lsls[i]) < mini:
        mini = len(lsls[i])
        k = i
v = []
v_1 = []
try:
    for j in range(maxi):
        for i in range(len(lsls)):
            v.append(lsls[i][j])
        if j + 1 == mini:
            raise IndexError

except IndexError:
    for i in range(len(lsls)):
        if len(lsls[i]) != 0:

            for j in range(len(lsls[i])):
                if j >= mini:
                    v_1.append(lsls[i][j])

print(v, ', ', v_1, sep='')

[1, 'a', 30, 2, 'b', 40], [3, 50, 60]
